spring.application.name=projeto-spring-boot-com-mysql

# Conexão com o servidor do banco de dados
spring.datasource.url=jdbc:mysql://192.168.205.100:3306/raul_m_db
# Usuário do banco
spring.datasource.username=raul_m
# Senha para o acesso do meu usuário
spring.datasource.password=00216099

spring.jpa.hibernate.ddl-auto=update




